server:
  port: 8080

spring:
  application:
    name: thumb-backend

  datasource:
    url: jdbc:mysql://localhost:3306/thumb_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    servlet:
      path: /api

  data:
    #Redis配置
    redis:
      database: 0
      host: 127.0.0.1
      password:
      timeout: 5000
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  setting:
    language: zh_cn
